### ISSUE TITLE
ERROR: Failure: OpenStackConfigException (Cloud devstack-admin was not found.)

### ISSUE THREAD

**Issue by smalljiaotongxue** [Huawei/python-openstacksdk#10]
如何解决如下问题：

ERROR: Failure: OpenStackConfigException (Cloud devstack-admin was not found.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/python2.7.12/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/python2.7.12/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/python2.7.12/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/cloud/SDK1/python-openstacksdk-master/openstack/tests/functional/volume_backup/v2/test_backup.py", line 17, in <module>
    from openstack.tests.functional import base
  File "/home/cloud/SDK1/python-openstacksdk-master/openstack/tests/functional/base.py", line 43, in <module>
    cloud = occ.get_one_cloud(opts.cloud, argparse=opts)
  File "/usr/local/python2.7.12/lib/python2.7/site-packages/os_client_config/config.py", line 1038, in get_one_cloud
    config = self._get_base_cloud_config(cloud)
  File "/usr/local/python2.7.12/lib/python2.7/site-packages/os_client_config/config.py", line 458, in _get_base_cloud_config
    name=name))
OpenStackConfigException: Cloud devstack-admin was not found.

**Comment by IamFive** [comment]
funcional test 创建使用本地配置文件来创建 connection，对应的文档在 [connection from config file](https://developer.openstack.org/sdks/python/openstacksdk/users/guides/connect_from_config.html)。

实际操作的时候，可以在 ~/.config/openstack 目录下添加 clouds.yaml，文件内容如下（把****替换成实际的值）
```
clouds:
  test_cloud:
    region_name: eu-de
    auth:
      auth_url: ********
      username: **********
      password: **********
      project_id: **********
      domain_id: **********
  devstack-admin:
    region_name: eu-de
    auth:
      auth_url: ********
      username: **********
      password: **********
      project_id: **********
      domain_id: **********

```

**Comment by smalljiaotongxue** [comment]
SDKException: SSL exception connecting to https://10.190.209.230:11111/v3: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

我在clouds.yaml配置了    verify : False。为什么还会报ssl的错误。能否协助帮忙看一下。

**Comment by IamFive** [comment]
这个不太清楚诶，我看下源码，你稍等

**Comment by IamFive** [comment]
```
clouds:
  test_cloud:
    region_name: eu-de
    insecure: True
    auth:
      auth_url: ********
      username: **********
      password: **********
      project_id: **********
      domain_id: **********
  devstack-admin:
    region_name: eu-de
    insecure: True
    auth:
      auth_url: ********
      username: **********
      password: **********
      project_id: **********
      domain_id: **********
```
